[formatter.nix]
command = "alejandra"
includes = [ "*.nix" ]
excludes = [ "nix/materialized/*" ]

# cabal-fmt breaks multi-line description

[formatter.haskell]
command = "ormolu"
options = [
    "--mode", "inplace",
    "--check-idempotence",
]
includes = ["*.hs"]
