---
name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.nixos.org https://cache.iog.io 
      - uses: cachix/cachix-action@v10
        with:
          name: shlevy
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#all --no-update-lock-file --no-link --print-build-logs
      - run: nix develop . --command treefmt --fail-on-change
